name: Jinja2
description: Renders Jinja2 templates
inputs:
  template:
    description: 'Path or contents of the template'
    required: true
  template-format:
    description: 'To be used with the "template" input, can be one of: string, file'
    required: false
    default: string
  variables:
    description: 'Path or contents of the variables'
    required: false
  variables-format:
    description: 'To be used with the "variables" input, can be one of: env, env_file, ini, ini_file, yaml, yaml_file, json, json_file'
    required: false
    default: yaml
outputs:
  output:
    description: 'Contents of the rendered template'
    value: ${{ steps.renderer.outputs.output }}
runs:
  using: composite
  steps:
  - id: cli
    shell: bash
    run: python ${{ github.action_path }}/main.py
    env:
      INPUT_TEMPLATE: ${{ inputs.template }}
      INPUT_TEMPLATE-FORMAT: ${{ inputs.template-format }}
      INPUT_VARIABLES: ${{ inputs.variables }}
      INPUT_VARIABLES-FORMAT: ${{ inputs.variables-format }}
      INPUT_STRICT: ${{ inputs.strict }}

  - uses: docker://ghcr.io/swaglive/jinja2:3.1.2
    with:
      args: >
        --format ${{ steps.cli.outputs.variables-format }}
        --outfile ${{ steps.cli.outputs.output }}
        --strict
        ${{ steps.cli.outputs.template }}
        ${{ steps.cli.outputs.variables }}

  - id: renderer
    shell: bash
    run: |
      {
        echo 'output<<EOF'
        cat ${{ steps.cli.outputs.output }}
        echo ''
        echo 'EOF'
      } | tee -a $GITHUB_OUTPUT > /dev/null
