name: Jinja2
description: Renders Jinja2 templates
inputs:
  template:
    description: 'Path to the template file'
    required: true
  template-format:
    description: 'To be used with the "template" input, can be one of: file, pipe'
    required: false
    default: file
  variables:
    description: 'Path to the variables file'
    required: false
  variables-format:
    description: 'To be used with the "variables" input, can be one of: env, env_file, ini, ini_file, yaml, yaml_file, json, json_file'
    required: false
    default: json
  output:
    description: 'Destination write rendered template to. One of: env, file'
    required: false
    default: /dev/stdout
  output-format:
    description: 'To be used with the "output" input, can be one of: env, file'
    required: false
    default: file
  strict:
    description: 'Fails on missing values'
    required: false
    default: false
runs:
  using: docker
  # image: docker://ghcr.io/swaglive/jinja2:3.1.2
  image: Dockerfile
  # args: [
  #   '--format', '${{ github.env.STATE_variables-format }}',
  #   '--outfile', '${{ github.env.STATE_output }}',
  #   '${{ github.env.STATE_template }}',
  #   '${{ github.env.STATE_variables }}'
  # ]
  args: [
    "--help"
  ]
  pre-entrypoint: pre-entrypoint.py
  # post-entrypoint: ./post-entrypoint.py