name: Jinja2
description: Renders Jinja2 templates
inputs:
  template:
    description: 'Path to the template file'
    required: true
  template-format:
    description: 'To be used with the "template" input, can be one of: file, pipe'
    required: false
    default: file
  variables:
    description: 'Path to the variables file'
    required: false
  variables-format:
    description: 'To be used with the "variables" input, can be one of: env, env_file, ini, ini_file, yaml, yaml_file, json, json_file'
    required: false
    default: json
  strict:
    description: 'Fails on missing values'
    required: false
    default: false
outputs:
  output:
    description: 'Contents of the rendered template'
    value: ${{ steps.renderer.outputs.output }}
runs:
  using: composite
  steps:
  - id: cli
    shell: bash
    run: python main.py
    env:
      INPUT_TEMPLATE: ${{ inputs.template }}
      INPUT_TEMPLATE-FORMAT: ${{ inputs.template-format }}
      INPUT_VARIABLES: ${{ inputs.variables }}
      INPUT_VARIABLES-FORMAT: ${{ inputs.variables-format }}
      INPUT_STRICT: ${{ inputs.strict }}

  - uses: docker://ghcr.io/swaglive/jinja2:3.1.2
    with:
      args: >
        --format ${{ steps.cli.outputs.variables-format }}
        --outfile ${{ steps.cli.outputs.output }}
        ${{ steps.cli.outputs.template }}
        ${{ steps.cli.outputs.variables }}

  - id: renderer
    shell: bash
    run: |
      {
        echo 'output<<EOF'
        cat ${{ steps.cli.outputs.output }}
        echo 'EOF'
      } >> $GITHUB_OUTPUT
