name: Job Summary

on:
  push:
  workflow_dispatch:

jobs:
  generate-job-summary:
    name: Generate Job Summary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Job Summary
      id: job-summary
      uses: ./
      with:
        template: .github/templates/job-summary.md.jinja
        variables: |-
          {
            "jobs": 1,
            "steps": ["a", "b", "c"]
          }

    - name: Save Job Summary
      run: tee $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary.outputs.output }}'