name: Job Summary

on:
  push:
  workflow_dispatch:

jobs:
  generate-job-summary:
    name: Generate Job Summary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Job Summary
      id: job-summary-json
      uses: ./
      with:
        template: .github/workflows/test/job-summary.md.jinja
        variables-format: json
        variables: |-
          {
            "jobs": "json",
            "steps": ["a", "b", "c"]
          }

    - name: Generate Job Summary
      id: job-summary-yaml
      uses: ./
      with:
        template: .github/workflows/test/job-summary.md.jinja
        variables-format: yaml
        variables: |-
          job: yaml
          steps:
            - a
            - b
            - c

    - name: Generate Job Summary
      id: job-summary-json-file
      uses: ./
      with:
        template: .github/workflows/test/job-summary.md.jinja
        variables: .github/workflows/test/variables.json
        variables-format: json-file

    - name: Generate Job Summary
      id: job-summary-yaml-file
      uses: ./
      with:
        template: .github/workflows/test/job-summary.md.jinja
        variables: .github/workflows/test/variables.yaml
        variables-format: yaml-file

    - name: Generate Job Summary
      id: job-summary-template
      uses: ./
      with:
        template-format: string
        template: |-
          * Jobs: {{ jobs }}
          * Steps
            - a
            - b
            - c 
            {%- for step in steps %}
            - {{ step }}
            {%- endfor %}
        variables: |-
          {
            "jobs": "json",
            "steps": ["a", "b", "c"]
          }

    - name: Save Job Summary
      run: |
        tee -a $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary-json.outputs.output }}'
        tee -a $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary-yaml.outputs.output }}'
        tee -a $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary-json-file.outputs.output }}'
        tee -a $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary-yaml-file.outputs.output }}'
        tee -a $GITHUB_STEP_SUMMARY <<< $'${{ steps.job-summary-template.outputs.output }}'