name: Job Summary

on:
  push:
  workflow_dispatch:

jobs:
  generate-job-summary:
    name: Generate Job Summary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: echo $GITHUB_STEP_SUMMARY
    - run: stat $GITHUB_STEP_SUMMARY
    - run: cat $GITHUB_STEP_SUMMARY

    - name: Generate Job Summary
      uses: ./
      with:
        template: .github/templates/job-summary.md.jinja
        output: GITHUB_STEP_SUMMARY
        output-format: env
        variables: |-
          {
            "jobs": 1,
            "steps": ["a", "b", "c"]
          }

    - run: echo $GITHUB_STEP_SUMMARY
    - run: stat $GITHUB_STEP_SUMMARY
    - run: cat $GITHUB_STEP_SUMMARY